acseo_typesense:
    # Typesense host settings
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
    # Collection settings
    collections:
        posts:
            entity: 'App\Entity\Post'
            fields:
                id:
                    name: id
                    type: primary
                sortable_id:
                    entity_attribute: id
                    name: sortable_id
                    type: int32
                title:
                    name: title
                    type: string
                summary:
                    name: summary
                    type: string
                content:
                    name: content
                    type: string
                createdAt:
                    name: createdAt
                    type: datetime
            default_sorting_field: sortable_id