version: '3'

services:
###> doctrine/doctrine-bundle ###
    database:
        ports:
            - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
###< symfony/mailer ###

###< symfony/typesense ###
    typesense:
        image: typesense/typesense:0.22.0
        environment:
            TYPESENSE_DATA_DIR: /data
            TYPESENSE_API_KEY: 123
        volumes:
            - /tmp/typesense-server-data:/data
        ports:
            - 8108:8108
        restart: "no"
###< symfony/typesense ###

